services:
  app:
    image: localhost:5000/cwa:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3002:3000"
    env_file:
      - .env
