import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";
import boundariesPlugin from "eslint-plugin-boundaries";

const NATIVE_IMPORTS = {
  group: [
    "@capacitor/*",
    "@capacitor-firebase/*",
    "@capgo/*",
    "firebase",
    "firebase/*",
  ],
  message: "Access native APIs via @/lib/native/* wrappers.",
};

const PUSH_IMPORTS = {
  group: ["firebase-admin", "firebase-admin/*"],
  message: "Send push through @/lib/push.",
};

const OBSERVABILITY_IMPORTS = {
  group: ["pino", "pino/*", "prom-client"],
  message: "Log and measure through @/lib/observability/*.",
};

const NATIVE_FILES = "src/lib/native/**/*.{ts,tsx}";
const PUSH_FILES = "src/lib/push.ts";
const OBSERVABILITY_FILES = "src/lib/observability/**/*.{ts,tsx}";

const restrictedImports = (files, ignores, patterns) => ({
  files: [files],
  ...(ignores.length > 0 ? { ignores } : {}),
  rules: {
    "no-restricted-imports": ["error", { patterns }],
  },
});

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/generated/**",
    // Build artifact of `npm run build:worker`, not source.
    "worker.js",
    "worker-instrument.js",
    // Capacitor native projects (generated by `npx cap add`)
    "ios/**",
    "android/**",
    // Agent scratch space, including sibling git worktrees — never our source.
    ".claude/**",
    // iCloud Drive conflict copies (`hub 2.ts`) — duplicates, never our source.
    "**/* [0-9].*",
  ]),
  eslintConfigPrettier,
  {
    plugins: {
      boundaries: boundariesPlugin,
    },
    settings: {
      "boundaries/elements": [
        { type: "app", pattern: "src/app/**/*" },
        { type: "use-cases", pattern: "src/use-cases/**/*" },
        { type: "worker", pattern: "src/worker/**/*" },
        {
          type: "feature-facade",
          pattern: "src/features/*/{facade,index,commands}.ts",
        },
        { type: "feature-internal", pattern: "src/features/*/services/**/*" },
        { type: "shared", pattern: "src/components/ui/**/*" },
      ],
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "error",
      "boundaries/dependencies": [
        2, // Error
        {
          default: "disallow",
          rules: [
            {
              from: { type: "app" },
              allow: [
                { to: { type: "use-cases" } },
                { to: { type: "feature-facade" } },
                { to: { type: "shared" } },
              ],
            },
            {
              from: { type: "use-cases" },
              allow: [{ to: { type: "feature-facade" } }],
            },
            {
              // The worker is a boundary layer like actions.ts: it carries no
              // session and calls inwards, never sideways into services.
              from: { type: "worker" },
              allow: [
                { to: { type: "use-cases" } },
                { to: { type: "feature-facade" } },
              ],
            },
            {
              from: { type: "feature-facade" },
              allow: [{ to: { type: "feature-internal" } }],
            },
            {
              from: { type: "feature-internal" },
              allow: [{ to: { type: "shared" } }],
            },
          ],
        },
      ],
    },
  },
  // Native APIs go through the semantic wrappers in src/lib/native/*, push
  // through @/lib/push, logging and metrics through @/lib/observability/* —
  // each scope repeats the restrictions it is not itself exempt from, because
  // a later block sharing the same files would override an earlier one.
  restrictedImports(
    "src/**/*.{ts,tsx}",
    [NATIVE_FILES, PUSH_FILES, OBSERVABILITY_FILES],
    [NATIVE_IMPORTS, PUSH_IMPORTS, OBSERVABILITY_IMPORTS],
  ),
  restrictedImports(NATIVE_FILES, [], [PUSH_IMPORTS, OBSERVABILITY_IMPORTS]),
  restrictedImports(PUSH_FILES, [], [NATIVE_IMPORTS, OBSERVABILITY_IMPORTS]),
  restrictedImports(OBSERVABILITY_FILES, [], [NATIVE_IMPORTS, PUSH_IMPORTS]),
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/observability/logger.ts", "**/*.test.{ts,tsx}"],
    rules: {
      "no-console": "error",
    },
  },
  {
    files: ["src/components/character/bloub/**"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // shadcn-generated code (overwritten by `npx shadcn add`) — don't lint it
    // against rules the upstream registry doesn't satisfy yet.
    files: ["src/components/ui/**", "src/hooks/use-mobile.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
