import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";
import boundariesPlugin from "eslint-plugin-boundaries";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/generated/**",
    // Capacitor native projects (generated by `npx cap add`)
    "ios/**",
    "android/**",
  ]),
  eslintConfigPrettier,
  {
    plugins: {
      boundaries: boundariesPlugin,
    },
    settings: {
      "boundaries/elements": [
        { type: "app", pattern: "src/app/**/*" },
        { type: "use-cases", pattern: "src/use-cases/**/*" },
        { type: "feature-facade", pattern: "src/features/*/{facade,index}.ts" },
        { type: "feature-internal", pattern: "src/features/*/services/**/*" },
        { type: "shared", pattern: "src/components/ui/**/*" },
      ],
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "error",
      "boundaries/dependencies": [
        2, // Error
        {
          default: "disallow",
          rules: [
            {
              from: { type: "app" },
              allow: [
                { to: { type: "use-cases" } },
                { to: { type: "feature-facade" } },
                { to: { type: "shared" } },
              ],
            },
            {
              from: { type: "use-cases" },
              allow: [{ to: { type: "feature-facade" } }],
            },
            {
              from: { type: "feature-facade" },
              allow: [{ to: { type: "feature-internal" } }],
            },
            {
              from: { type: "feature-internal" },
              allow: [{ to: { type: "shared" } }],
            },
          ],
        },
      ],
    },
  },
  {
    // Native APIs go through the semantic wrappers in src/lib/native/*
    // (SSR-safe, isNativePlatform-guarded) — never through raw plugins.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/native/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@capacitor/*"],
              message: "Access native APIs via @/lib/native/* wrappers.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/components/character/bloub/**"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // shadcn-generated code (overwritten by `npx shadcn add`) — don't lint it
    // against rules the upstream registry doesn't satisfy yet.
    files: ["src/components/ui/**", "src/hooks/use-mobile.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
