import type { LucideIcon } from "lucide-react";
import {
  Bike,
  Home,
  Calendar,
  MapPin,
  MessageCircle,
  User,
  Users,
  Bell,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  Plus,
  Check,
  CheckCheck,
  X,
  Clock,
  Sun,
  Sunset,
  Phone,
  BatteryMedium,
  Lock,
  Key,
  Warehouse,
  TriangleAlert,
  Heart,
  Globe,
  Settings,
  ClipboardList,
  Send,
  Star,
  Search,
  RotateCcw,
  Download,
  Building2,
  Gift,
  Shield,
  Sparkles,
  Wrench,
  LayoutDashboard,
  Route,
  MoreHorizontal,
  Info,
  Pencil,
  ExternalLink,
  Flag,
  Languages,
  LogOut,
  Euro,
  Smile,
  SunMedium,
  Armchair,
  List,
  Trash2,
  Cloud,
  Wind,
  Trophy,
  Ticket,
  Navigation,
  ArrowUpRight,
  Zap,
  Play,
  Mail,
  Award,
  Compass,
  Camera,
} from "lucide-react";

/* The vanilla mockup's icon vocabulary, mapped onto lucide. Data-driven UI
   (notifications, tab configs, tiles) refers to icons by these names. */
const ICONS: Record<string, LucideIcon> = {
  bike: Bike,
  home: Home,
  calendar: Calendar,
  mapPin: MapPin,
  chat: MessageCircle,
  user: User,
  users: Users,
  bell: Bell,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  plus: Plus,
  check: Check,
  checkCheck: CheckCheck,
  x: X,
  clock: Clock,
  sun: Sun,
  sunset: Sunset,
  phone: Phone,
  battery: BatteryMedium,
  lock: Lock,
  key: Key,
  warehouse: Warehouse,
  alert: TriangleAlert,
  heart: Heart,
  globe: Globe,
  settings: Settings,
  clipboard: ClipboardList,
  send: Send,
  star: Star,
  search: Search,
  reset: RotateCcw,
  download: Download,
  building: Building2,
  gift: Gift,
  shield: Shield,
  sparkles: Sparkles,
  wrench: Wrench,
  dashboard: LayoutDashboard,
  route: Route,
  more: MoreHorizontal,
  info: Info,
  pencil: Pencil,
  externalLink: ExternalLink,
  flag: Flag,
  languages: Languages,
  logout: LogOut,
  euro: Euro,
  smile: Smile,
  whatsapp: MessageCircle,
  sunMedium: SunMedium,
  armchair: Armchair,
  list: List,
  trash: Trash2,
  cloud: Cloud,
  wind: Wind,
  trophy: Trophy,
  ticket: Ticket,
  navigation: Navigation,
  arrowUpRight: ArrowUpRight,
  zap: Zap,
  play: Play,
  mail: Mail,
  award: Award,
  compass: Compass,
  camera: Camera,
};

export function Icon({
  name,
  size,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const C = ICONS[name] || Bike;
  return (
    <C
      size={size}
      className={className}
      aria-hidden="true"
    />
  );
}
