import {
  Armchair,
  Bike,
  CalendarDays,
  ChartNoAxesColumn,
  CircleQuestionMark,
  Globe,
  GraduationCap,
  House,
  Languages,
  LayoutDashboard,
  LogOut,
  MapPinned,
  MessagesSquare,
  PanelLeft,
  Route,
  Settings,
  ShieldCheck,
  Users,
  Warehouse,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/lib/commands";

export const ICONS: Record<IconKey, LucideIcon> = {
  overview: LayoutDashboard,
  home: House,
  calendar: CalendarDays,
  training: GraduationCap,
  rides: Route,
  members: Users,
  passengers: Armchair,
  bikes: Bike,
  locations: Warehouse,
  chat: MessagesSquare,
  reports: ChartNoAxesColumn,
  chapters: MapPinned,
  countries: Globe,
  settings: Settings,
  help: CircleQuestionMark,
  admin: ShieldCheck,
  pilot: Bike,
  passenger: Armchair,
  language: Languages,
  sidebar: PanelLeft,
  signOut: LogOut,
};
